import csv
import qrcode
from PIL import Image, ImageDraw, ImageFont

# Load data from CSV file


with open('registrations.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile, fieldnames=['Team Name', 'Team Category', 'Member1', 'Contact', 'Member2', 'Member3','Language','Institution', 'Username', 'password'])

    for row in reader:
        team_name = row['Team Name']
        team_category = row['Team Category']
        username = row['Username']
        password = row['password']
        member1 = row['Member1']
        member2 = row['Member2']
        member3 = row['Member3']
        cont1 = row['Contact']
        lang = row['Language']
        inst = row['Institution']

        # Create QR code with event details
        event_details = f"Event: Code Air 2.0 \nTeam Name: {team_name}\nInstitute: {inst}\nTeam Category: {team_category} \nMember 1: {member1}\nMember 2: {member2}\nMember 3: {member3}\nUsername: {username}\nPassword: {password}"
        qr = qrcode.QRCode(version=1, box_size=5, border=2)
        qr.add_data(event_details)
        qr.make(fit=True)
        qr_img = qr.make_image(fill_color='black', back_color='white')

        # Resize QR code to fit ticket
        qr_width, qr_height = qr_img.size
        max_qr_size = 150
        if qr_width > max_qr_size or qr_height > max_qr_size:
            qr_img = qr_img.resize((max_qr_size, max_qr_size), resample=Image.BOX)

        # Create ticket image
        ticket_width = 600
        ticket_height = 300
        ticket_img = Image.new('RGB', (ticket_width, ticket_height), color='white')
        draw = ImageDraw.Draw(ticket_img)

        # Add event logo to ticket
        logo_width = 200  # desired width of the logo
        logo_height = int(logo_width * 804 / 2880)  # calculate height to maintain aspect ratio

        event_logo = Image.open('event_logo2.png')
        event_logo = event_logo.resize((logo_width, logo_height), resample=Image.BOX)
        ticket_img.paste(event_logo, (ticket_width - logo_width - 10, 10), mask=event_logo)

        mlsa_logo = Image.open("mlsa.png")
        mlsa_width = 200  # desired width of the logo
        mlsa_height = int(mlsa_width * 369 / 759)  # calculate height to maintain aspect ratio
        mlsa_logo = mlsa_logo.resize((mlsa_width, mlsa_height), resample=Image.BOX)
        ticket_img.paste(mlsa_logo, (-20, -15), mask=mlsa_logo)

        # Add QR code to ticket
        qr_x = 10
        qr_y = (ticket_height - qr_img.height) // 2
        ticket_img.paste(qr_img, (qr_x, qr_y))

        # Add team details
        team_name_font = ImageFont.truetype('arial.ttf', size=18)
        about_font = ImageFont.truetype('arial.ttf', size=12)

        boldfont = ImageFont.truetype('arialbd.ttf', size=18)
        draw.text((300, 80), f"Code Air 2.0", font=boldfont, fill='black')
        draw.text((200, 110), f"Team Name: {team_name} ({team_category})  - {inst}", font=team_name_font, fill='black')
        team_members_font = ImageFont.truetype('arial.ttf', size=16)
        draw.text((200, 140), f"Members:\n{member1}  - {cont1}\n{member2}\n{member3}", font=team_members_font, fill='black')

        draw.text((17, 230), f"In case of any query Contact", font=about_font, fill='black')
        draw.text((17, 243), f"Floor Invigilator", font=about_font, fill='black')
        draw.text((17, 280), f"Generated by Think Tank", font=about_font, fill='black')

        if lang == "python":
            prog_logo = Image.open("py.png").convert('RGBA')
            size = (100, 100)  # desired square size
            prog_logo = prog_logo.resize(size)  # resize image
            ticket_img.paste(prog_logo, (430,140), mask=prog_logo)
        
        elif lang == "c":
            prog_logo = Image.open("c.png").convert('RGBA')
            size = (100, 100)  # desired square size
            prog_logo = prog_logo.resize(size)  # resize image
            ticket_img.paste(prog_logo, (430,140), mask=prog_logo)
        
        elif lang == "cpp":
            prog_logo = Image.open("cpp.png").convert('RGBA')
            size = (100, 100)  # desired square size
            prog_logo = prog_logo.resize(size)  # resize image
            ticket_img.paste(prog_logo, (430,140), mask=prog_logo)

        elif lang == "javascript":
            prog_logo = Image.open("js.png").convert('RGBA')
            size = (100, 100)  # desired square size
            prog_logo = prog_logo.resize(size)  # resize image
            ticket_img.paste(prog_logo, (430,140), mask=prog_logo)


        # Add username and password
        username_font = ImageFont.truetype('arial.ttf', size=14)
        draw.text((450, 260), f"Username: {username}", font=username_font, fill='black')
        password_font = ImageFont.truetype('arial.ttf', size=14)
        draw.text((450, 280), f"Password: {password}", font=password_font, fill='black')

        # Save ticket image
        ticket_img.save(f"./tickets/{team_name}.png")